### PR TITLE
Windows Containers : fix typo and dead link

### PR DESCRIPTION
**Pull request by Styxxy**

### CODE REVIEW

**Comment by Styxxy** [comment]
Partially duplicate with #1426

**Comment by Styxxy** [comment]
@mattbriggs Can you look at those PRs?

**Comment by mattbriggs** [comment]
@[Styxxy](https://github.com/Styxxy) Thanks for your contribution. Can you make your PR against main rather than 'live'? Thanks! Matt

**Comment by mattbriggs** [comment]
changed to : https://github.com/MicrosoftDocs/Virtualization-Documentation-Private/pull/783

**Pull request closed without merging**
