### PR TITLE
Removed instructions for manual image creation

### PR DESCRIPTION
**Pull request by nicholasdille**
Docker has revolutionized container management by adding automation. The documentation seems to advocate that manually creating an image is the first step into Docker. I could not disagree more. New users should be taught to embrace automation and understand the importance of standardization and repeatability. Therefore, I propose to remove the whole section.

### CODE REVIEW

**Comment by StefanScherer** [comment]
Looks much cleaner now. 😀

**Comment by StefanScherer** [comment]
(I have to admit that I used docker commit etc. in my Windows workshops, but this is an guided tour and not a self pace tutorial so I can explain the audience that we will do this only once and quickly switch to a source coded description in a Dockerfile. It is good to understand how each layer works and the impact some commands have in respect of image layer sizes. )

For this doc page I‘m +1 to only show the correct way.

**Comment by scooley** [comment]
Ping @PatrickLang @taylorb-microsoft for their assessment.  Seems reasonable to me.

**Comment by PatrickLang** [comment]
Docker's page only shows `docker build` not `docker commit`

https://docs.docker.com/get-started/part2/

LGTM

**Pull request merged**
