### PR TITLE
Update export_import.md

### PR DESCRIPTION
**Pull request by doctordns**
Removed future tense to improve readability and updated one sentence for clearer meaning. 
Minor changes!

### CODE REVIEW

**Comment by scooley** [comment]
Much better :).  Thank you

**Comment by doctordns** [comment]
How did I cause those conflicts??

**Comment by scooley** [comment]
You didn't -- I moved a pile of files around awhile back :).  I'm manually merging in goodness and closing the PR.

Let me know if you have any concerns with that approach.

**Comment by doctordns** [comment]
The approach works fine for me!

**Pull request closed without merging**
