### PR TITLE
Updated the powershell command

### PR DESCRIPTION
**Pull request by Karthikmuthiahr**
People copy the commands literally, so updated the PS commands to reflect vEthernet (VmNat) from ethernet

### CODE REVIEW

**Comment by Karthikmuthiahr** [comment]
#sign-off

**Comment by Karthikmuthiahr** [comment]
#sign-off

**Review by mattbriggs — APPROVED** [review]

**Comment by mattbriggs** [comment]
sign-off

**Comment by BarbaraSelden** [comment]
HELP @mattbriggs has this merged?

**Comment by mattbriggs** [comment]
@BarbaraSelden yes. Thanks

> [mattbriggs](https://github.com/mattbriggs) merged commit [467655d](https://github.com/MicrosoftDocs/Virtualization-Documentation/commit/467655d3c8104a54729d3b760f5468601f551843) into MicrosoftDocs:live [2 hours ago](https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1712#event-6253405914)

**Pull request merged**
