### PR TITLE
Clarify differences in isolation=hyperv support for Windows 10 vs Windows Server

### PR DESCRIPTION
**Pull request by PatrickLang**
My chart was a bit confusing - there are actually differences between what works on WIndows 10 and Windows Server. Splitting this out to separate columns.

### CODE REVIEW

**Comment by PatrickLang** [comment]
ping @ryansimmen - does this make more sense?

**Comment by friism** [comment]
@PatrickLang so host  OS version `16299.*` can run container OS version `14393.*` with process isolation?

image

**Comment by PatrickLang** [comment]
@friism good point, fixing now. bad copy/paste on my part as I split that apart

**Comment by friism** [comment]
@PatrickLang man, you just got my hopes up...

**Pull request merged**
