### PR TITLE
Jmesser updatenetworkcleanup

### PR DESCRIPTION
**Pull request by JMesser81**
NOT READY TO MERGE
 - Need a better way to clean-up default nat network
 - how can I link output from docker network ls to specific vSwitches and NetNat instances

### CODE REVIEW

**Comment by msabansal** [comment]
This looks good and should cleanup everything. What are the other requirements from the script that you need help with?

**Comment by scooley** [comment]
Ping @JMesser81 @kallie-b -- ready to merge?

**Comment by scooley** [comment]
Ping @JMesser81 and @kallie-b

**Comment by kallie-b** [comment]
Replaced by [this commit](https://github.com/MicrosoftDocs/Virtualization-Documentation/commit/cdce1de7021225e59db22fcf123ea97b1c892713).

**Pull request closed without merging**
