### PR TITLE
Update supported-guest-os.md

### PR DESCRIPTION
**Pull request by peppekerstens**
inclcomplete info on mainstream guest OS support; Enhanced Session Mode does not work with Windows 10 Home Guest OS

### CODE REVIEW

**Comment by scooley** [comment]
Hyper-V in general isn't available on Windows 10 Home Edition.

**Comment by scooley** [comment]
Fair point.  Can you add guest OS?  Then I'll merge

**Comment by peppekerstens** [comment]
Hello Sarah,

My discription may not have been complete. Enhanced Session Mode does not work when using Windows 10 Home as a guest OS.

Tested a clean install with latest MSDN bits on both Windows 10 build 17025.rs_prerelease.171020-1626 and Windows 2016 10.0.14393 as being a hypervisor for the client. Did not test on earlier Hyper-V platform, but I assume the same because of next.

Also tested conversion from Windows 10 Home to Windows 10 Pro by using same install (key change). After this (and a reboot) Enhanced Session Mode works. So I assume this limitation is deliberate on Windows 10 Home as being a guest OS.

Above will probably have minimum impact on average production environment (not using W10Home as guest) but out took me >3 hours to find this out while just wanting to test some random thingy (assumed error on Hyper-V config/W10 bits donwload/install etc etc ). Bummer. :(

**Comment by scooley** [comment]
Got it :).

**Pull request merged**
