### PR TITLE
Updates documentation to match script changes in the SDN repository.

### PR DESCRIPTION
**Pull request by gkudra-msft**
Microsoft/SDN#184 improved the scripts to no longer require a `-gateway` parameter, and split the sample services to not include port-mapping by default in order to properly demonstrate scaling.

### CODE REVIEW

**Comment by gkudra-msft** [comment]
ping @PatrickLang and @scooley. 😄

**Comment by scooley** [comment]
Uuuuug, merge conflicts.  Ping @PatrickLang

**Comment by gkudra-msft** [comment]
Oh jeez... That's not how I should resolve conflicts.. Sec

**Comment by gkudra-msft** [comment]
That's better. Fixed! @scooley

**Pull request merged**
