### PR TITLE
fix: Resolve merge conflicts

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
Hit this trying to read one of the affected articles. If I got the merge wrong, feel free to fix internally

**Comment by BenjaminArmstrong** [comment]
There are a lot of deletions here - with no obvious contribution

**Comment by nschonni** [comment]
@BenjaminArmstrong these are Git conflicts where this repo has run into trouble when you've merged branches or between your public and private repo.
EX: on https://docs.microsoft.com/en-ca/virtualization/windowscontainers/about/index

If you don't want to land this, please talk to your repo admin that handles your git syncing about fixes this as the content on these pages is broken because of it

**Comment by eross-msft** [comment]
@nschonni  @BenjaminArmstrong  Just to follow up on this, scooley overwrote the newly-released containers content, causing these merge conflicts. We believe it's that she didn't pull down from live to her branch before making changes and merging. I've now fixed all of the merge conflict-related issues. Please let me know if you see any additional ones. Thanks!

**Comment by nschonni** [comment]
Thanks @eross-msft!
Looks like these files still have the merge conflicts
- hyperv-samples/benarm-powershell/GuestNameCheck.ps1
- hyperv-samples/benarm-powershell/README.md
- virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md

**Pull request closed without merging**
