### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Comment by gewarren** [comment]
#sign-off

**Comment by gewarren** [comment]
@alvinmorales1 Can you take a look at this PR? Not sure the process to get it merged in this repo.

**Comment by gewarren** [comment]
Ping @alvinmorales1.

**Comment by gewarren** [comment]
#please-merge

**Comment by gewarren** [comment]
@thecloudtaylor Could you merge this PR?

**Review by thecloudtaylor — APPROVED** [review]

**Pull request merged**
